### PR TITLE
[MRG] added flake8 to travis

### PR DESCRIPTION
**Pull request by davidmeunier79**
added flake8command  to travis.xml

### CODE REVIEW

**Comment by jasmainak** [comment]
Set the PR title to [MRG] when you are ready ...

**Comment by davidmeunier79** [comment]
I rebased a lot of commits (60+ -> 7) but I believe this is worse keeping some info as I have done quite a lot of cleaning on the way....

**Comment by annapasca** [comment]
I can merge it after the checks are completed!

**Comment by jasmainak** [comment]
@annapasca just a note, I disabled a regular "merge" method in github settings as it's not the recommended way. You can either do "squash and merge" or you can do a "rebase and merge"

**Review by jasmainak — APPROVED** [review]
Woot! Good job @davidmeunier79

**Comment by davidmeunier79** [comment]
@jasmainak I see it means all modifications will be under one commit message, does that mean I have  to make the merge in this case???

**Comment by jasmainak** [comment]
@davidmeunier79 merged! Thanks.

No, anyone can merge. And you don't have to "squash and merge". You can do "rebase and merge"

**Comment by davidmeunier79** [comment]
> @davidmeunier79 merged! Thanks.
> 
> No, anyone can merge. And you don't have to "squash and merge". You can do "rebase and merge"

OK thanks

**Pull request merged**
