### PR TITLE
Try unittest

### PR DESCRIPTION
**Pull request by davidmeunier79**
Added some unitests for all the nii_to_conmat.py pipelines + datasets with functional and segmented anatomical MRI, as well as some required template mask to extract time series.

### CODE REVIEW

**Comment by jasmainak** [comment]
@davidmeunier79 you made commits with an email address that is not linked in your github profile. You could add this email address to your github profile so it links to you

**Comment by davidmeunier79** [comment]
@jasmainak  I do not see where my e-mail adress is wrong, can you tell me where this info is located?

**Comment by jasmainak** [comment]
If you do `git log`, what is the email address you see in your commits? You can add that email address in github using `git config` command: https://help.github.com/articles/setting-your-username-in-git/. And in github you should have a _matching_ email address: https://help.github.com/articles/setting-your-commit-email-address-on-github/

**Comment by davidmeunier79** [comment]
Ok this is what I did. Also, I have done some tests with PEP8, in the newer pull request #11 , so it is better to close this PR without merging and merge the new one

**Comment by jasmainak** [comment]
okay sounds good

**Pull request closed without merging**
