### PR TITLE
Add api

### PR DESCRIPTION
**Pull request by annapasca**
Added list of functions in https://neuropycon.github.io/graphpype/api.html

### CODE REVIEW

**Review by jasmainak — APPROVED** [review]

**Comment by annapasca** [comment]
@davidmeunier79 do you have idea why travis crashes? 
I added some doc for API

**Comment by davidmeunier79** [comment]
It seems it is coming from a change of version of py.test:

platform linux -- Python 3.6.9, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /home/travis/build/neuropycon/graphpype
plugins: cov-2.8.1
collecting ... 

And on the previous version that passed the test:
platform linux -- Python 3.6.9, pytest-5.2.0, py-1.8.0, pluggy-0.13.0
rootdir: /home/travis/build/neuropycon/graphpype
plugins: cov-2.7.1
collected 65 items     

Does that makes any sense to anyone? I will try to see if the version that passed (https://github.com/neuropycon/graphpype/pull/43) is now failing

**Comment by davidmeunier79** [comment]
Yes it is indeed because of that, see https://github.com/neuropycon/graphpype/pull/46. I am running now a test with forcing version pytest-cov==2.7.1 (the previous version that was working earlier)

**Comment by davidmeunier79** [comment]
Now it is working for the test with Python 3.6, but still fails with python 2.7.


Logs = 

platform linux2 -- Python 2.7.16, pytest-4.6.6, py-1.8.0, pluggy-0.13.0

rootdir: /home/travis/build/neuropycon/graphpype

plugins: cov-2.7.1

collecting ... 


Previous logs =



platform linux2 -- Python 2.7.16, pytest-4.6.5, py-1.8.0, pluggy-0.13.0

rootdir: /home/travis/build/neuropycon/graphpype

plugins: cov-2.7.1

collected 65 items

**Comment by davidmeunier79** [comment]
This is unpredictable:
https://travis-ci.org/neuropycon/graphpype/builds/599150569?utm_source=github_status&utm_medium=notification
and 
https://travis-ci.org/neuropycon/graphpype/builds/599164334?utm_source=github_status&utm_medium=notification
were the same, but it is not the same build (once python3.6, once python2.7) that crashed!

**Comment by davidmeunier79** [comment]
Hi Annalisa,

it seems it is an issue with pytest or pytest-cov, as the version of these packages are different than the previous build that was OK. I have been trying to see what went wrong but it is quite unpredictable. I have tried different option (see the discussion on the PR you opened), but I cannot get both python 2.7 and 3.6 to work together!
-> my solution = I removed the environnement 2.7 !

Hopefully this is only temporary...

I will let you know once it is fixed.

A+

David



________________________________
De : Annalisa Pascarella <notifications@github.com>
Envoyé : jeudi 17 octobre 2019 14:20
À : neuropycon/graphpype <graphpype@noreply.github.com>
Cc : David Meunier <david_meunier_79@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [neuropycon/graphpype] Add api (#44)


@davidmeunier79<https://github.com/davidmeunier79> do you have idea why travis crashes?
I added some doc for API

**Comment by davidmeunier79** [comment]
Could it be related to this issue?
http://doc.pytest.org/en/latest/py27-py34-deprecation.html

**Comment by annapasca** [comment]
@davidmeunier79 if for you is ok could you merge?

**Comment by davidmeunier79** [comment]
@annapasca How did you get it to pass??? I am still strugling with my own PR https://github.com/neuropycon/graphpype/pull/45

**Comment by annapasca** [comment]
@davidmeunier79 I didn't do anything o.O
I only run again the process in CircleCi

**Pull request merged**
