### PR TITLE
Autopep8

### PR DESCRIPTION
**Pull request by davidmeunier79**
I have been using autopep8 on the previous branch I used to format code according to PEP8 requirements. Also, added my e-mail on local config for commits, seems to have changed the way the commits are understood.

### CODE REVIEW

**Comment by jasmainak** [comment]
> added my e-mail on local config for commits, seems to have changed the way the commits are understood.

also add the email on github :)

**Comment by jasmainak** [comment]
@davidmeunier79 please merge when you are happy. We don't know the code well enough to review a 9000 line diff :)

also, try to avoid merge commits if you can ... you should never pull/merge in a professional workflow. Only rebase

**Comment by jasmainak** [comment]
I meant non-fast forward pulls. Fast-forward pulls are fine ...

**Comment by davidmeunier79** [comment]
Ok great, if I remove the dependancy on nipype plugins if passes the test OK.

@jasmainak I am not sure I understand your last point? Indeed I have tested the whole afternoon why it was crashing with nipype plugins, you mean I should have done a new PR every time?

**Comment by jasmainak** [comment]
umm ... I meant the following:

Let's say you created a branch `dev` from `master` and Etienne made another branch `fancy-feature` from master. You both work on your branches. But Etienne makes a pull request first and it is merged into master. Now, you have conflicts with master. What should you do?

option 1: fetch the latest master and merge it into `dev`
option 2: fetch the latest master but rebase `dev` on top of `master`

Option 2 is what you should do. But from what I see, you have been doing option 1

**Comment by jasmainak** [comment]
The difference between the two options is that option 2 results in a clean commit history. The commits in `master` should be organized in blocks of pull requests. Something like this:

o-o-o-o-x-x-x-x-x-x-x-y-y-y-y-y-y

where 'o', 'x', and 'y' are the commits of different pull requests. If you follow option 1, you will have something like this:

o-x-o-y-y-x-o-y-o-y-x-x-x-y-x-x-x-y

**Pull request merged**
